name: "Delete Unused Daily Entries"

on:
  schedule:
    - cron: "30 23 * * FRI"  # Every Friday at 11:30 PM
  workflow_dispatch:

jobs:
  aggregate-mentions:
    runs-on: ubuntu-latest
    name: Delete Unused Entries
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
            python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install dateutil requests
      - name: Run script
        run: |
          python delete_unused_daily_entry.py
        env:
            NOTION_INTEGRATION_SECRET: ${{ secrets.NOTION_INTEGRATION_SECRET }}
